version: "2"
services:
  mysql:
    container_name: gateway-mysql
    image: mysql:5.7
    ports: [ 13306:3306 ]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default

networks:
  default:
    external:
      name: lura_net

volumes:
  mysql_data: