server:
  port: 22307
spring:
  application:
    name: lura-gateway-server
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://www.baidu.com
        predicates:
        - Path=/


application.auth:
  login-url: http://localhost:8013/auth/login
  check-url: http://localhost:8013/auth/check
  logout-url: http://localhost:8013/auth/logout
