server:
  port: 22307
spring:
  application:
    name: lura-gateway-server
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://www.baidu.com
        predicates:
        - Path=/test
      - id: aliyun_route
        uri: https://www.aliyun.com/
        predicates:
          - Path=/product/**
      - id: httpbin_route
        uri: https://httpbin.org
        predicates:
          - Path=/httpbin/**
        filters:
          - RewritePath=/httpbin/(?<segment>.*), /$\{segment}


