server:
  port: 22307
spring:
  application:
    name: lura-gateway-server
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://www.baidu.com
        predicates:
        - Path=/


