server:
  port: 22307
spring:
  application:
    name: lura-gateway-server
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://www.baidu.com
        predicates:
        - Path=/test
      - id: auth_route
        uri: http://localhost:8013
        predicates:
          - Path=/auth/**
      - id: product_service
        uri: lb://ecommerce-product-service
        predicates:
          - Path=/product/**
      - id: order_service
        uri: lb://ecommerce-order-service
        predicates:
          - Path=/order/**
      - id: aliyun_route
        uri: https://www.aliyun.com/
        predicates:
          - Path=/product/**
      - id: httpbin_route
        uri: https://httpbin.org
        predicates:
          - Path=/httpbin/**
        filters:
          - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
      globalcors:
        cors-configurations:
          '[/**]':
#            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#          add-to-simple-url-handler-mapping: true


application.whitelist:
  - url: /product/product/**
    method: GET
