server:
  port: 8080
spring:
  application:
    name: lura-gateway-server
  cloud:
    gateway:
      routes:
      - id: auth_route
        uri: lb://lura-framework-auth-server
        predicates:
          - Path=/auth/**
      - id: product_service
        uri: lb://ecommerce-product-service
        predicates:
          - Path=/product/**
      - id: order_service
        uri: lb://ecommerce-order-service
        predicates:
          - Path=/order/**
      globalcors:
        cors-configurations:
          '[/**]':
#            allowCredentials: true
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
#          add-to-simple-url-handler-mapping: true


