server:
  port: 8013
spring:
  application:
    name: lura-framework-auth-server
  cloud:
    nacos:
      discovery:
        group: LURA-FRAMEWORK
    sentinel:
      datasource:
        flow:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-flow-rules
            groupId: SYSTEM
            rule-type: flow
