server:
  port: 8080
spring:
  application:
    name: lura-framework-auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lura_framework_user
    password: password
    url: jdbc:mysql://${DB_HOST:localhost}:3306/lura_framework?allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
